language: python

# Here we use anaconda for builds other than 2.7, since it provides the
# simplest interface for running different versions of Python

virtualenv:
    # set up our 2.7 to use the system site packages correctly
    system_site_packages: true

env:
    - PYTHON=2.6 DEPS=full
    - PYTHON=2.7 DEPS=full
    - PYTHON=3.3 DEPS=full
    # PYTHON=2.7 DEPS=minimal  # No optional deps yet

before_install:
    - if [ "${PYTHON}" != "2.7" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh;
        ./miniconda.sh -b;
        export PATH=/home/$USER/anaconda/bin:$PATH;
        conda update --yes conda;
      else
        travis_retry sudo apt-get -qq update;
      fi;

install:
    - if [ "${PYTHON}" != "2.7" ]; then
        conda create -n testenv --yes --quiet pip python=$PYTHON;
        source activate testenv;
        conda install --yes --quiet scipy pandas nose matplotlib;
      else
        travis_retry sudo apt-get -qq install python-scipy python-nose python-matplotlib;
        pip install pandas;
      fi;
    - pip install -q coveralls nose-timer flake8
    - python setup.py build
    - python setup.py install
    - SRC_DIR=$(pwd)
    - cd ~
    # We will run tests from vispy dir to test our install worked
    - PLP_DIR=$(python -c 'import pylinkparse;print(pylinkparse.__path__[0])')
    # Link coverage to src dir, coveralls should be run from there (needs git calls)
    - ln -s ${PLP_DIR}/../.coverage ${SRC_DIR}/.coverage
    - ln -s ${SRC_DIR}/pylinkparse/tests/data ${PLP_DIR}/tests/data
    - ln -s ${SRC_DIR}/.coveragerc ${PLP_DIR}/../.coveragerc
    - ln -s ${SRC_DIR}/setup.cfg ${PLP_DIR}/../setup.cfg

script:
    - cd ${PLP_DIR}/../
    - # Nose-timer has bugs on 3+ as of Jan 2014
    - if [ "${PYTHON}" == "2.7" ]; then
        nosetests --with-timer --timer-top-n 10;
      else
        nosetests;
      fi
    # Require strict adherence to PEP8 and pyflakes (can use "# noqa" to skip)
    - cd ${SRC_DIR}
    - make flake;

after_success:
    # Need to run from source dir to execute appropriate "git" commands
    - coveralls;
